### ISSUE TITLE
Direct contact with you for Skoda MIB2

### ISSUE THREAD

**Issue by em1ter** [lprot/MIB-Tools#1]
Hello, @lprot
I've been communicating with you for some time earlier using drive2, but now this way of communication is restricted for me due to the policy of that portal. My nickname on the drive2 is EmiteR, you may remember me.
I need some advice with Skoda MIB2 and unfortunately I don't know any other ways to communicate with you.
My email is emiters.garage@gmail.com
Please mail me if you don't mind communicating with me.
Thank you!

**Comment by bugmegbik** [comment]
You can browse firmwares on:
https://mibsolution.one
user:guest pass:guest

Check and add knowledge:
https://mibwiki.one

Latest M.I.B. version for MHI2 patching.
Always update before using!
http://mib.mibsolution.one

пт, 18 мар. 2022 г., 13:26 em1ter ***@***.***>:

**Comment by lprot** [comment]
@em1ter Make sure you read FAQ at the end of the https://www.drive2.com/l/573969809784439237/
