### ISSUE TITLE
Delphi 2 Boot Loop Recovery - Help request

### ISSUE THREAD

**Issue by TheHellSite** [lprot/MIB-Tools#3]
Hello lprot,

I know this is not related to your repository directly but I would really appreciate your help and also have no problem with compensating your time!

Is there any way I can contact you through some messenger app of your choice or discord?
Sadly I am unable to register at drive2.ru, it always gives me error 400.

This is my problem: https://www.digital-eliteboard.com/threads/mib2-std-delphi-recovern-upgrade-p0642d-zu-p0879d-fehlgeschlagen.534660/

**Comment by lprot** [comment]
https://www.torproject.org/de/download/
